### ISSUE TITLE
tty device name as function argument

### ISSUE THREAD

**Issue by ghost** [jswrenn/beep#2]
Would you consider adding the ability to make the tty device be passed in as a function argument?

You haven't worked on this since early 2018, so it's worth a try asking first before I create a crate based on this, adding this.

/dev/tty0 is Linux. Other operating systems use different named devices (/dev/tty00 on NetBSD, where /dev/tty0 by default does not exist).

**Comment by ghost** [comment]
My take on this could be wrong, but the example provided, with the exact same crate versions beep uses, throws (with the change to tty00, same with tty0):

```
 RUST_BACKTRACE=1 cargo run --verbose
       Fresh autocfg v0.1.5
       Fresh nodrop v0.1.13
       Fresh lazy_static v1.3.0
       Fresh typenum v1.10.0
       Fresh libc v0.2.60
       Fresh generic-array v0.5.1
       Fresh num-traits v0.2.8
       Fresh dimensioned v0.6.0
       Fresh beep v0.2.1 (https://c.n0.is/beep2?branch=default#39703d16)
       Fresh beeping v0.1.0 (/home/ng0/src/util/src/sandboxes/rustc/beeping)
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/beeping`
thread 'main' panicked at 'Could not open /dev/tty00: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libcore/result.rs:827
  10: core::ops::function::FnOnce::call_once
             at /home/ng0/.cargo/git/checkouts/beep2-d15359fc2ffc9cb7/39703d1/src/lib.rs:19
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libcore/ops/function.rs:231
  11: lazy_static::lazy::Lazy<T>::get::{{closure}}
             at /home/ng0/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:28
  12: std::sync::once::Once::call_once::{{closure}}
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libstd/sync/once.rs:220
  13: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:387
  14: std::sync::once::Once::call_once
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libstd/sync/once.rs:220
  15: <beep::DEVICE as core::ops::deref::Deref>::deref
             at /home/ng0/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:27
             at /home/ng0/.cargo/git/checkouts/beep2-d15359fc2ffc9cb7/39703d1/<::lazy_static::__lazy_static_internal macros>:12
             at /home/ng0/.cargo/git/checkouts/beep2-d15359fc2ffc9cb7/39703d1/<::lazy_static::__lazy_static_internal macros>:13
  16: beep::beep
             at /home/ng0/.cargo/git/checkouts/beep2-d15359fc2ffc9cb7/39703d1/src/lib.rs:54
  17: beeping::main
             at src/main.rs:9
  18: std::rt::lang_start::{{closure}}
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libstd/rt.rs:64
  19: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:85
  21: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  22: std::rt::lang_start
             at /usr/work/lang/rust/work/rustc-1.36.0-src/src/libstd/rt.rs:64
  23: main
  24: _init
```

This is on NetBSD 9 (8.99.48) amd64 with rustc 1.36.0

**Comment by jswrenn** [comment]
Writing to `/dev/*` requires elevated permissions on most (all?) systems. To run the example, try:
```rust
cargo build --example song ; sudo target/debug/examples/song
```

> Would you consider adding the ability to make the tty device be passed in as a function argument?

I'm open to this. Here's how I'd like to perhaps approach the problem:
 - `beep` should pick the 'right' device by default
 - we can introduce an unsafe function `unix::beep` (or something similar) which additionally consumes a `RawFd`

(Unfortunately, as with #1, I don't have other machines to test on.)

However, I found a purportedly NetBSD-compatible `beep` that writes to `/dev/console`: https://github.com/jnlon/beep/blob/master/main.c#L222

Even after changing  `/dev/tty0` to `/dev/console`, the example works for me (using ArchLinux).

Does changing `/dev/tty0` to `/dev/console` work for you?

**Comment by ghost** [comment]
Acknowledged, and I'll get back to you as soon as I can, I'm on a tight schedule right now.

**Comment by ghost** [comment]
> Even after changing /dev/tty0 to /dev/console, the example works for me (using ArchLinux).
> Does changing /dev/tty0 to /dev/console work for you?

The main change is that the error disappears. The fact that I hear nothing expected, I have to look into this as it could be a setting in my OS etc. I could also suggest looking into the audio subsystem of netbsd, but I presume this is beyond the scope of a program which goes "beep".

Your proposed solutions sound okay, if this works. I can test on NetBSD, FreeBSD, Debian, if you require this.
